server.port=8080

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=appagendadecontatos@gmail.com
spring.mail.password=bqxebmrjichenjlr
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.rabbitmq.addresses= amqps://wggzhuka:X0WbwZffhRrQ5HztDS3SJmA1uIYzCjHw@beaver.rmq.cloudamqp.com/wggzhuka
spring.rabbitmq.queue=ms.email